# ===================================================================
# DM JHipster Sample Spring Cloud Config.
# ===================================================================

# Property used on app startup to check the config server status
configserver:
    name: DM JHipster Registry config server
    status: Connected to the JHipster Registry config server, using https://github.com/datamanagementitalia/jhipster !

# Default JWT secret token (to be changed in production!)
jhipster:
    security:
        authentication:
            jwt:
                secret: bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl
               
# DM 
dm:
    loggin:
        logpath: \app\log\

# DM - Rabbit Config
spring:
    rabbitmq:
        host: 10.10.252.54
        port: 5672
        password: guest
        username: guest
        listener:
            simple:
                acknowledge-mode: manual
                prefetch: 1
